name: "build"

on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8, 10, 12, 13]

    steps:
      - uses: actions/checkout@v1

      - name: "Config"
        run: |
          git config --global user.email "git-ci@techinity.com"
          git config --global user.name "gitci"

      - name: "Install dependencies"
        run: npm install

      - name: "Build"
        run: npm run build

      - name: "Test"
        run: npm run test

      - name: "Lint"
        run: npm run lint

      - name: "Semantic version"
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false
        run: |
          npm run release -- --dry-run
