name: "release"
on:
  push:
    branches:
      - 'master'

jobs:
  validation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
      - uses: actions/checkout@v1

      - name: "Config"
        run: |
          echo "Release triggered by ${{github.actor}}"
          echo "Commit ${{github.event.commits[0].message}}"
          git config --global user.email "git-ci@techinity.com"
          git config --global user.name "gitci"

      - name: "Install dependencies"
        run: npm install

      - name: "Build"
        run: npm run build

      - name: "Test"
        run: npm run test

      - name: "Semantic version"
        if: |
          contains(github.event.commits[0].message, '[skip ci]') == false
        run: |
          npm run release
